# Generated by Django 4.2.7 on 2026-05-07 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_start', models.TimeField(default='09:00:00')),
                ('work_end', models.TimeField(default='18:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sla_deadline', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('assigned', 'Назначена'), ('done', 'Выполнена'), ('violated', 'Просрочена')], default='new', max_length=10)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.engineer')),
                ('required_competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.competence')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_solve_time_minutes', models.IntegerField(help_text='Сколько минут инженер решает задачу этой компетенции')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.competence')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.engineer')),
            ],
            options={
                'unique_together': {('engineer', 'competence')},
            },
        ),
    ]
